# Generated by Django 4.2.2 on 2023-07-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0003_product_remainder_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(verbose_name='Картинка'),
        ),
    ]
